#!/usr/bin/env bash

. ./conf/config

distri=`cat /etc/issue | awk '{ printf $1 }'`
# testing
case $distri in
	"Ubuntu" ) PM='apt-get';;
	"CentOS" ) PM='yum';;
esac
PM_SUDO="sudo $PM"

# install necessary libs and tools
#$PM_SUDO update
$PM_SUDO install -y gcc make git openssl openssh-server

# install rbenv and ruby-build
if [ "`type rbenv`" != *"not found"* ]; then
	echo "--> rbenv has been installed in `which rbenv`"
else
	echo "--> installing rbenv ..."
	git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
	echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
	echo 'eval "$(rbenv init -)"' >> ~/.bashrc
	source ~/.bashrc

	if [ "`type rbenv`" != *"not found"* ]; then
		echo "--> rbenv has been installed successfully in `which rbenv`"
	fi

	echo "--> installing ruby-build ..."
	git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

	if [ "`rbenv install | grep 'Usage'`" != "" ]; then
		echo "--> ruby-build has been installed successfully(`rbenv install --versioin`)"
	fi
fi

# install ruby
rbenv install ${RUBY_DEFAULT}
